"use client";

import { Printer } from "lucide-react";
import { Button } from "@/components/ui/button";

export function PaymentConfirmation({
  applicationReference,
  nomineeName,
  paymentReference,
  receiptReference,
  amount,
  paymentDate,
  verifiedDate,
}: {
  applicationReference: string;
  nomineeName: string;
  paymentReference: string;
  receiptReference: string;
  amount: string;
  paymentDate: string;
  verifiedDate: string;
}) {
  return (
    <section className="surface mt-6 rounded-lg p-6 print:border-0 print:shadow-none">
      <div className="flex flex-wrap items-start justify-between gap-4">
        <div>
          <p className="text-xs uppercase tracking-wider text-antique-gold">
            System-generated payment confirmation
          </p>
          <h2 className="mt-2 font-display text-3xl font-semibold">
            GBE Awards payment confirmation
          </h2>
        </div>
        <Button
          type="button"
          variant="outline"
          className="print:hidden"
          onClick={() => window.print()}
        >
          <Printer data-icon="inline-start" />
          Print or save PDF
        </Button>
      </div>
      <dl className="mt-6 grid gap-4 sm:grid-cols-2">
        {[
          ["Receipt reference", receiptReference],
          ["Payment reference", paymentReference],
          ["Application reference", applicationReference],
          ["Nominee", nomineeName],
          ["Amount", amount],
          ["Payment date", paymentDate],
          ["Verification date", verifiedDate],
          ["Issuer", "Global Business Excellence Awards"],
        ].map(([label, value]) => (
          <div key={label} className="border-b pb-3">
            <dt className="text-xs uppercase tracking-wider text-muted-foreground">
              {label}
            </dt>
            <dd className="mt-1 font-medium">{value}</dd>
          </div>
        ))}
      </dl>
      <p className="mt-6 text-sm leading-6 text-muted-foreground">
        This confirmation was generated by the GBE Awards portal. For
        verification or assistance, contact info@gbeaward.com.
      </p>
    </section>
  );
}
