import {
  Activity,
  Award,
  Banknote,
  BookOpen,
  CircleHelp,
  FileArchive,
  FolderOpen,
  Gauge,
  Mail,
  MessageSquare,
  Settings,
  ShieldCheck,
  Tags,
  UserRound,
  UsersRound,
} from "lucide-react";
export const adminNavigation = [
  { href: "/admin", label: "Dashboard", icon: Gauge },
  { href: "/admin/applications", label: "Applications", icon: FileArchive },
  { href: "/admin/applicants", label: "Applicants", icon: UsersRound },
  { href: "/admin/payments", label: "Payments", icon: Banknote },
  { href: "/admin/files", label: "Files", icon: FolderOpen },
  { href: "/admin/communications", label: "Communications", icon: Mail },
  { href: "/admin/exports", label: "Exports", icon: BookOpen },
  { href: "/admin/reports", label: "Reports", icon: Activity },
  { href: "/admin/categories", label: "Categories", icon: Tags },
  { href: "/admin/cycles", label: "Award cycles", icon: Award },
  { href: "/admin/staff", label: "Staff", icon: ShieldCheck },
  { href: "/admin/settings", label: "Settings", icon: Settings },
  { href: "/admin/activity", label: "Activity", icon: Activity },
];
export const portalNavigation = [
  { href: "/portal", label: "Overview", icon: Gauge },
  { href: "/portal/applications", label: "My application", icon: FileArchive },
  { href: "/portal/documents", label: "Documents", icon: FolderOpen },
  { href: "/portal/payment", label: "Payment", icon: Banknote },
  { href: "/portal/messages", label: "Messages", icon: MessageSquare },
  { href: "/portal/profile", label: "Profile", icon: UserRound },
  { href: "/portal/security", label: "Security", icon: ShieldCheck },
  { href: "/portal/help", label: "Help", icon: CircleHelp },
];
