export const rolePermissions: Record<string, readonly string[]> = {
  super_admin: ["*"],
  admin: [
    "applications.view",
    "applications.view_all",
    "applications.edit",
    "applications.change_status",
    "applications.approve",
    "applications.reject",
    "applications.release_outcome",
    "payments.view",
    "payments.verify",
    "files.view",
    "files.manage",
    "messages.send",
    "exports.create",
    "applicants.manage",
    "configuration.manage",
    "audit.view",
  ],
  reviewer: [
    "applications.view",
    "applications.change_status",
    "files.view",
    "messages.send",
  ],
  finance: [
    "applications.view",
    "applications.view_all",
    "payments.view",
    "payments.verify",
    "files.view",
    "exports.create",
  ],
  support: [
    "applications.view",
    "applications.view_all",
    "files.view",
    "messages.send",
    "applicants.manage",
  ],
};
