"use client";
import { useState } from "react";
import { zodResolver } from "@hookform/resolvers/zod";
import { Controller, useForm } from "react-hook-form";
import { AlertCircle, ArrowRight, CheckCircle2, LoaderCircle, LockKeyhole } from "lucide-react";
import { Alert, AlertDescription, AlertTitle } from "@/components/ui/alert";
import { Button } from "@/components/ui/button";
import { Checkbox } from "@/components/ui/checkbox";
import { Field, FieldDescription, FieldError, FieldGroup, FieldLabel, FieldSet, FieldLegend } from "@/components/ui/field";
import { Input } from "@/components/ui/input";
import { Select, SelectContent, SelectGroup, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Progress } from "@/components/ui/progress";
import { declarationText } from "@/config/brand";
import { publicApplicationSchema, type PublicApplicationInput } from "@/lib/validation/application";
import { FilePicker, type SelectedUpload } from "@/components/uploads/file-picker";
import { Turnstile } from "./turnstile";

type Category = { id: string; name: string };
type InitiateResponse = { ok: true; data: { sessionToken: string; uploads: Array<{ id: string; url: string; headers: Record<string,string> }> } } | { ok: false; message: string; fieldErrors?: Record<string,string[]> };
function uploadFile(upload: SelectedUpload, target: { url: string; headers: Record<string,string> }, onProgress: (value: number) => void) { return new Promise<void>((resolve, reject) => { const xhr = new XMLHttpRequest(); xhr.open("PUT", target.url); Object.entries(target.headers).forEach(([key,value]) => xhr.setRequestHeader(key,value)); xhr.upload.onprogress = (event) => event.lengthComputable && onProgress(Math.round(event.loaded / event.total * 100)); xhr.onload = () => xhr.status >= 200 && xhr.status < 300 ? resolve() : reject(new Error("Upload failed")); xhr.onerror = () => reject(new Error("Upload interrupted")); xhr.send(upload.file); }); }

export function NominationForm({ categories, unavailable }: { categories: Category[]; unavailable?: boolean }) {
  const [supporting, setSupporting] = useState<SelectedUpload[]>([]); const [payment, setPayment] = useState<SelectedUpload[]>([]); const [fileError, setFileError] = useState<string>(); const [progress, setProgress] = useState(0); const [stage, setStage] = useState<"idle"|"preparing"|"uploading"|"finalising"|"success">("idle"); const [reference, setReference] = useState(""); const [startedAt] = useState(() => Date.now()); const [idempotencyKey] = useState(() => crypto.randomUUID());
  const form = useForm<PublicApplicationInput>({ resolver: zodResolver(publicApplicationSchema), defaultValues: { nomineeName:"", designation:"", industrySector:"", businessWebsite:"", email:"", phone:"", categoryId:"", declarationAccepted:false, declarationText, turnstileToken:"", honeypot:"", startedAt, idempotencyKey } });
  const submit = form.handleSubmit(async (values) => { if (payment.length !== 1) { setFileError("Choose one payment slip or screenshot."); return; } setFileError(undefined); const files = [...supporting,...payment]; setStage("preparing"); try { const response = await fetch("/api/public/applications/initiate", { method:"POST", headers:{"content-type":"application/json"}, body:JSON.stringify({ ...values, files: files.map(({id,file,kind}) => ({ id, name:file.name, size:file.size, type:file.type, kind })) }) }); const initiated = await response.json() as InitiateResponse; if (!initiated.ok) throw new Error(initiated.message); setStage("uploading"); const totals = new Map<string,number>(); for (const upload of files) { const target = initiated.data.uploads.find((item) => item.id === upload.id); if (!target) throw new Error("An upload destination was not created."); await uploadFile(upload,target,(value) => { totals.set(upload.id,value); setProgress(Math.round([...totals.values()].reduce((a,b)=>a+b,0)/files.length)); }); } setStage("finalising"); const complete = await fetch("/api/public/applications/complete", { method:"POST", headers:{"content-type":"application/json"}, body:JSON.stringify({ sessionToken:initiated.data.sessionToken,idempotencyKey:values.idempotencyKey }) }); const result = await complete.json(); if (!result.ok) throw new Error(result.message); setReference(result.data.reference); setStage("success"); form.reset(); setSupporting([]); setPayment([]); } catch (error) { setStage("idle"); form.setError("root", { message:error instanceof Error ? error.message : "We could not submit your nomination. Your entered information is safe. Please try again." }); } });
  if (stage === "success") return <section className="glass-feature rounded-xl p-8 text-center md:p-12" aria-live="polite"><CheckCircle2 className="mx-auto mb-5 size-12 text-[#23604e]" /><h2 className="font-display text-4xl font-semibold">Nomination received</h2><p className="mx-auto mt-3 max-w-lg text-graphite">Thank you. Your official application reference is shown below and has been sent to your email address.</p><p className="mx-auto mt-6 w-fit rounded-md border border-champagne bg-gold-wash px-5 py-3 font-mono text-lg font-semibold tracking-wider">{reference}</p></section>;
  const error = form.formState.errors;
  return <form onSubmit={submit} noValidate className="surface overflow-hidden rounded-lg" aria-describedby={error.root ? "form-error" : undefined}>{error.root ? <Alert variant="destructive" className="m-6" id="form-error"><AlertCircle /><AlertTitle>We could not submit the nomination</AlertTitle><AlertDescription>{error.root.message}</AlertDescription></Alert> : null}{unavailable ? <Alert className="m-6"><AlertCircle /><AlertTitle>Applications are not open yet</AlertTitle><AlertDescription>The award cycle and categories have not been configured. Please contact info@gbeaward.com.</AlertDescription></Alert> : null}
  <FormSection number="1" title="Nominee details"><FieldGroup><div className="grid gap-5 md:grid-cols-2"><ControlledInput form={form} name="nomineeName" label="Full Name / Company Name" required /><ControlledInput form={form} name="designation" label="Designation" description="Complete this only when nominating an individual." /></div><ControlledInput form={form} name="industrySector" label="Industry / Business Sector" required /><ControlledInput form={form} name="businessWebsite" label="Business Website" description="If applicable" inputMode="url" /></FieldGroup></FormSection>
  <FormSection number="2" title="Contact details"><FieldGroup><ControlledInput form={form} name="email" label="Email Address" required inputMode="email" /><ControlledInput form={form} name="phone" label="Phone Number" required inputMode="tel" description="Include your international country code, for example +94." /></FieldGroup></FormSection>
  <FormSection number="3" title="Nomination"><Controller control={form.control} name="categoryId" render={({field,fieldState}) => <Field data-invalid={fieldState.invalid}><FieldLabel htmlFor="categoryId">Award Nomination / Category <span aria-hidden className="text-destructive">*</span></FieldLabel><Select value={field.value} onValueChange={field.onChange} disabled={unavailable}><SelectTrigger id="categoryId" className="h-[50px] w-full bg-white" aria-invalid={fieldState.invalid}><SelectValue placeholder="Choose an award category" /></SelectTrigger><SelectContent><SelectGroup>{categories.map((category) => <SelectItem key={category.id} value={category.id}>{category.name}</SelectItem>)}</SelectGroup></SelectContent></Select><FieldError errors={[fieldState.error]} /></Field>} /></FormSection>
  <FormSection number="4" title="Documents"><FieldGroup><Field><FieldLabel>Supporting Documents</FieldLabel><FieldDescription>Optional · up to five files</FieldDescription><FilePicker kind="supporting_document" files={supporting} onChange={setSupporting} /></Field><Field data-invalid={Boolean(fileError)}><FieldLabel>Payment Slip or Screenshot <span aria-hidden className="text-destructive">*</span></FieldLabel><FieldDescription>One payment-proof file is required.</FieldDescription><FilePicker kind="payment_proof" files={payment} onChange={setPayment} error={fileError} /></Field></FieldGroup></FormSection>
  <FormSection number="5" title="Confirmation"><FieldSet><FieldLegend className="sr-only">Nomination declaration and security verification</FieldLegend><Controller control={form.control} name="declarationAccepted" render={({field,fieldState}) => <Field orientation="horizontal" data-invalid={fieldState.invalid}><Checkbox checked={field.value} onCheckedChange={(checked) => field.onChange(checked === true)} aria-invalid={fieldState.invalid} id="declaration" /><div><FieldLabel htmlFor="declaration" className="font-normal">I confirm that the details provided are accurate and agree to the <a href="/terms" target="_blank" className="text-antique-gold underline">terms of the nomination process</a></FieldLabel><FieldError errors={[fieldState.error]} /></div></Field>} /><Controller control={form.control} name="turnstileToken" render={({field,fieldState}) => <Field data-invalid={fieldState.invalid}><Turnstile onToken={field.onChange} /><FieldError errors={[fieldState.error]} /></Field>} /><input type="text" tabIndex={-1} autoComplete="off" className="absolute -left-[9999px]" aria-hidden {...form.register("honeypot")} /></FieldSet>{stage !== "idle" ? <div className="mt-6" aria-live="polite"><div className="mb-2 flex justify-between text-sm"><span>{stage === "preparing" ? "Preparing secure uploads…" : stage === "uploading" ? "Uploading files…" : "Confirming your nomination…"}</span><span>{stage === "uploading" ? `${progress}%` : ""}</span></div><Progress value={stage === "preparing" ? 5 : stage === "finalising" ? 98 : progress} /></div> : null}<Button type="submit" disabled={stage !== "idle" || unavailable} className="ceremonial-button mt-6 h-12 w-full text-base font-semibold">{stage !== "idle" ? <LoaderCircle className="animate-spin" data-icon="inline-start" /> : null}Submit nomination <ArrowRight data-icon="inline-end" /></Button><p className="mt-4 flex items-center justify-center gap-2 text-center text-xs text-muted-foreground"><LockKeyhole aria-hidden /> Your information and files are transferred securely.</p></FormSection></form>;
}

function FormSection({ number,title,children }: { number:string; title:string; children:React.ReactNode }) { return <section className="border-b border-mist px-5 py-7 last:border-b-0 md:px-8 md:py-9"><h2 className="section-title mb-6"><span className="mr-2 text-antique-gold">{number}.</span>{title}</h2>{children}</section>; }
function ControlledInput({ form,name,label,description,required,inputMode }: { form:ReturnType<typeof useForm<PublicApplicationInput>>; name:keyof PublicApplicationInput; label:string; description?:string; required?:boolean; inputMode?:React.HTMLAttributes<HTMLInputElement>["inputMode"] }) { return <Controller control={form.control} name={name} render={({field,fieldState}) => <Field data-invalid={fieldState.invalid}><FieldLabel htmlFor={name}>{label} {required ? <span className="text-destructive" aria-hidden>*</span> : null}</FieldLabel>{description ? <FieldDescription>{description}</FieldDescription> : null}<Input {...field} value={typeof field.value === "string" ? field.value : ""} id={name} inputMode={inputMode} aria-invalid={fieldState.invalid} className="h-[50px] bg-white" /><FieldError errors={[fieldState.error]} /></Field>} />; }
